# Merge LDA , k means , textblov and vader for train set

In [1]:
## Import packages

import numpy as np
import pandas as pd
import copy

In [2]:
kmeans = pd.read_csv('kmeans_train_text.csv')
kmeans.head(5)

,id,title,author,text,label,K_means
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1,2
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,1
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,2
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,2
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,2

In [3]:
lda = pd.read_csv('lda_train_text_5.csv')
lda.head(5)

,Document_No,Dominant_Topic,Topic_Perc_Contrib,Keywords,Text
0,0,2.0,0.7499,i s t it the clinton trump people you hillary,"['house', 'dem', 'aide', 'we', 'didn', 't', 'e..."
1,1,2.0,0.6950,i s t it the clinton trump people you hillary,"['ever', 'feeling', 'life', 'circles', 'rounda..."
2,2,0.0,0.5489,s mr trump the said president state obama gove...,"['why', 'truth', 'might', 'get', 'you', 'fired..."
3,3,0.0,0.9062,s mr trump the said president state obama gove...,"['videos', 'civilians', 'killed', 'in', 'singl..."
4,4,0.0,0.4749,s mr trump the said president state obama gove...,"['print', 'an', 'iranian', 'woman', 'sentenced..."

In [4]:
trainVader = pd.read_csv('old/vaderkmeansdata.csv', encoding='latin-1')
trainVader.head(5)

,id,author,label,text,title,compound,K_means
0,0,Darrell Lucus,1,house dem aide didnt even see comeys letter ja...,house dem aide didnt even see comeys letter ja...,0.5431,0
1,1,Daniel J. Flynn,0,ever get feeling life circle roundabout rather...,flynn hillary clinton big woman campus breitbart,-0.4405,2
2,2,Consortiumnews.com,1,truth might get fired october tension intellig...,truth might get fired,0.9853,0
3,3,Jessica Purkiss,1,video civilian killed single u airstrike ident...,civilian killed single u airstrike identified,-0.9993,0
4,4,Howard Portnoy,1,print iranian woman sentenced six year prison ...,iranian woman jailed fictional unpublished sto...,-0.9517,0

In [5]:
trainTextblob = pd.read_csv('textblobText.csv' , encoding='latin-1')
trainTextblob.head(5)

,id,title,author,text,label,text_clean,tb_Pol,tb_Subj
0,0,House Dem Aide: We Didnât Even See Comeyâs...,Darrell Lucus,House Dem Aide: We Didnât Even See Comeyâs...,1,house dem aide didnt even see comeys letter ja...,0.026726,0.456226
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,ever get feeling life circle roundabout rather...,0.077613,0.485211
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,truth might get fired october tension intellig...,0.083994,0.418484
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,video civilian killed single u airstrike ident...,0.021485,0.251616
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,print iranian woman sentenced six year prison ...,0.047143,0.197143

In [6]:
print(kmeans.shape)
print(lda.shape)
print(trainVader.shape)
print(trainTextblob.shape)

(20800, 6)
(20800, 5)
(20800, 7)
(20800, 8)

In [11]:
def Sentiscore(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else:
        return 'Postive'

In [7]:
merged_train_data = pd.DataFrame(kmeans,columns=['id', 'title' , 'text' , 'K_means'])
merged_train_data['LDA_Dominant_Topic'] = lda['Dominant_Topic']
merged_train_data['text_vader_compound'] = trainVader['compound']
merged_train_data['text_vader_neg'] = trainVader['neg']
merged_train_data['text_vader_neu'] = trainVader['neu']
merged_train_data['text_vader_pos'] = trainVader['pos']
merged_train_data['tb_Pol'] = trainTextblob['tb_Pol']
merged_train_data['tb_Subj'] = trainTextblob['tb_Subj']
merged_test_data['Polarity_category'] = trainTextblob['tb_Pol'].apply(Sentiscore)
merged_train_data.head(4)

In [8]:
# print(merged_train_data.shape)
# merged_train_data.isna().sum()

In [9]:
# merged_train_data.dtypes

In [10]:
# merged_test_data.to_csv('merged_train_data.csv', index=False)
# dt_csv = pd.read_csv('merged_train_data.csv')