# Merge LDA , k means , textblov and vader for test set

In [1]:
## Import packages
import numpy as np
import pandas as pd
import copy

In [2]:
kmeans = pd.read_csv('kmeans_test_text.csv')
kmeans.head(5)

,id,title,author,text,K_means
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning...",0
1,20801,Russian warships ready to strike terrorists ne...,,Russian warships ready to strike terrorists ne...,1
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...,1
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different...",0
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...,1

In [3]:
lda = pd.read_csv('lda_test_text_5.csv')
lda.head(5)

,Document_No,Dominant_Topic,Topic_Perc_Contrib,Keywords,Text
0,0,1.0,0.6228,s mr said the trump i president it he in,"['palo', 'alto', 'calif', 'after', 'years', 's..."
1,1,4.0,0.9945,s the russia us war government said it world s...,"['russian', 'warships', 'ready', 'strike', 'te..."
2,2,1.0,0.7654,s mr said the trump i president it he in,"['videos', 'nodapl', 'native', 'american', 'le..."
3,3,1.0,0.4708,s mr said the trump i president it he in,"['if', 'don', 't', 'succeed', 'try', 'differen..."
4,4,2.0,0.6925,s i trump clinton the t it hillary election pe...,"['mins', 'ago', 'views', 'comments', 'likes', ..."

In [4]:
testVader = pd.read_csv('testVader.csv')
testVader.head(5)

,id,title,author,text,compound,neg,neu,pos
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning...",0.9957,0.028,0.898,0.074
1,20801,Russian warships ready to strike terrorists ne...,,Russian warships ready to strike terrorists ne...,-0.9670,0.171,0.729,0.100
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...,-0.9926,0.113,0.839,0.047
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different...",0.9981,0.023,0.839,0.138
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...,0.7650,0.012,0.908,0.080

In [5]:
testTextblob = pd.read_csv('testTextblob.csv')
testTextblob.head(5)

,id,title,author,text,text_clean,title_clean,tb_Pol,tb_Subj
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning...",palo alto calif year scorning political proces...,specter trump loosens tongue purse string sili...,0.071113,0.411889
1,20801,Russian warships ready to strike terrorists ne...,,Russian warships ready to strike terrorists ne...,russian warship ready strike terrorist near al...,russian warship ready strike terrorist near al...,0.076509,0.314263
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...,video nodapl native american leader vow stay w...,nodapl native american leader vow stay winter ...,-0.012060,0.343737
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different...",first dont succeed try different sport tim teb...,tim tebow attempt another comeback time baseba...,0.154540,0.427795
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...,min ago view comment like first time history f...,keiser report meme war,0.111806,0.335417

In [6]:
print(kmeans.shape)
print(lda.shape)
print(testVader.shape)
print(testTextblob.shape)

(5200, 5)
(5200, 5)
(5200, 8)
(5200, 8)

In [11]:
def Sentiscore(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else:
        return 'Postive'

In [15]:
merged_test_data = pd.DataFrame(kmeans,columns=['id', 'title' , 'text' , 'K_means'])
merged_test_data['LDA_Dominant_Topic'] = lda['Dominant_Topic']
merged_test_data['text_vader_compound'] = testVader['compound']
merged_test_data['text_vader_neg'] = testVader['neg']
merged_test_data['text_vader_neu'] = testVader['neu']
merged_test_data['text_vader_pos'] = testVader['pos']
merged_test_data['tb_Pol'] = testTextblob['tb_Pol']
merged_test_data['tb_Subj'] = testTextblob['tb_Subj']
merged_test_data['Polarity_category'] = testTextblob['tb_Pol'].apply(Sentiscore)

In [16]:
merged_test_data.head(4)

,id,title,text,K_means,LDA_Dominant_Topic,text_vader_compound,text_vader_neg,text_vader_neu,text_vader_pos,tb_Pol,tb_Subj,Polarity_category
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...","PALO ALTO, Calif. — After years of scorning...",0,1.0,0.9957,0.028,0.898,0.074,0.071113,0.411889,Postive
1,20801,Russian warships ready to strike terrorists ne...,Russian warships ready to strike terrorists ne...,1,4.0,-0.9670,0.171,0.729,0.100,0.076509,0.314263,Postive
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Videos #NoDAPL: Native American Leaders Vow to...,1,1.0,-0.9926,0.113,0.839,0.047,-0.012060,0.343737,Negative
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...","If at first you don’t succeed, try a different...",0,1.0,0.9981,0.023,0.839,0.138,0.154540,0.427795,Postive

In [17]:
print(merged_test_data.shape)
merged_test_data.isna().sum()

(5200, 12)

id                     0
title                  0
text                   0
K_means                0
LDA_Dominant_Topic     0
text_vader_compound    0
text_vader_neg         0
text_vader_neu         0
text_vader_pos         0
tb_Pol                 0
tb_Subj                0
Polarity_category      0
dtype: int64

In [18]:
merged_test_data.dtypes

id                       int64
title                   object
text                    object
K_means                  int64
LDA_Dominant_Topic     float64
text_vader_compound    float64
text_vader_neg         float64
text_vader_neu         float64
text_vader_pos         float64
tb_Pol                 float64
tb_Subj                float64
Polarity_category       object
dtype: object

In [19]:
merged_test_data.to_csv('merged_test_data.csv', index=False)
dt_csv = pd.read_csv('merged_test_data.csv')